import {
  ALargeSmallIcon,
  AlignLeftIcon,
  ArrowDownIcon,
  ArrowRightToLineIcon,
  ArrowUpIcon,
  BoldIcon,
  BracesIcon,
  CaseUpperIcon,
  CodeIcon,
  DivideIcon,
  DownloadIcon,
  FilePlusIcon,
  FolderPlusIcon,
  FolderSearchIcon,
  HashIcon,
  HeadingIcon,
  HighlighterIcon,
  ImageIcon,
  ImagePlusIcon,
  ItalicIcon,
  LinkIcon,
  ListIcon,
  ListOrderedIcon,
  ListTreeIcon,
  type LucideIcon,
  MessageSquareOffIcon,
  PackageIcon,
  PackagePlusIcon,
  QuoteIcon,
  RadicalIcon,
  ReplaceAllIcon,
  ReplaceIcon,
  SearchIcon,
  SigmaIcon,
  SquareFunctionIcon,
  SquareSigmaIcon,
  SubscriptIcon,
  SuperscriptIcon,
  TableIcon,
  TagIcon,
  UnderlineIcon,
  UploadIcon,
  WrenchIcon,
} from 'lucide-react'

/**
 * Icônes lucide des actions, par nom (`EditorAction.icon`). Liste explicite plutôt que l'index
 * complet de lucide : seules ces icônes entrent dans le bundle. Un outil qui utilise une autre
 * icône l'ajoute ici ; un nom inconnu affiche l'icône générique.
 */
const ACTION_ICONS: Record<string, LucideIcon> = {
  'a-large-small': ALargeSmallIcon,
  'align-left': AlignLeftIcon,
  'arrow-down': ArrowDownIcon,
  'arrow-right-to-line': ArrowRightToLineIcon,
  'arrow-up': ArrowUpIcon,
  bold: BoldIcon,
  braces: BracesIcon,
  'case-upper': CaseUpperIcon,
  code: CodeIcon,
  divide: DivideIcon,
  download: DownloadIcon,
  'file-plus': FilePlusIcon,
  'folder-plus': FolderPlusIcon,
  'folder-search': FolderSearchIcon,
  hash: HashIcon,
  heading: HeadingIcon,
  highlighter: HighlighterIcon,
  image: ImageIcon,
  'image-plus': ImagePlusIcon,
  italic: ItalicIcon,
  link: LinkIcon,
  list: ListIcon,
  'list-ordered': ListOrderedIcon,
  'list-tree': ListTreeIcon,
  'message-square-off': MessageSquareOffIcon,
  package: PackageIcon,
  'package-plus': PackagePlusIcon,
  quote: QuoteIcon,
  radical: RadicalIcon,
  replace: ReplaceIcon,
  'replace-all': ReplaceAllIcon,
  search: SearchIcon,
  sigma: SigmaIcon,
  'square-function': SquareFunctionIcon,
  'square-sigma': SquareSigmaIcon,
  subscript: SubscriptIcon,
  superscript: SuperscriptIcon,
  table: TableIcon,
  tag: TagIcon,
  underline: UnderlineIcon,
  upload: UploadIcon,
}

/** Icône d'une action (rien si l'action n'en déclare pas). */
export function ActionIcon({ name, className }: { name: string | undefined; className?: string }) {
  if (name === undefined) return null
  const Icon = ACTION_ICONS[name] ?? WrenchIcon
  return <Icon className={className} aria-hidden />
}
